-- ============================================================================
-- 001_baseline.sql — AthFuelPath PostgreSQL baseline schema
--
-- Generated by introspecting the FINAL schema produced by main branch's
-- db/setup.py + api/services/db_migrations.py::run_all() (68e37e9), NOT by
-- replaying that historical SQLite migration sequence. This file is the one
-- clean starting point for PostgreSQL; future schema changes are new
-- 002_*.sql / 003_*.sql files applied on top via db/postgres_migrate.py.
--
-- Type-mapping rules applied (see migration report Phase 2 for rationale):
--   INTEGER PRIMARY KEY AUTOINCREMENT  -> INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
--   REAL                               -> DOUBLE PRECISION
--   TEXT                               -> TEXT (unchanged)
--   SQLite BOOLEAN columns             -> PostgreSQL BOOLEAN (2 columns total —
--                                          parents.consent_confirmed, daily_targets.lea_alert)
--   Integer 0/1 flag columns           -> left as INTEGER (NOT converted to boolean —
--                                          preserves exact app read/write semantics)
--   TEXT timestamp columns             -> stay TEXT. DEFAULT CURRENT_TIMESTAMP and
--                                          DEFAULT (datetime('now')) both produced the
--                                          identical 'YYYY-MM-DD HH:MM:SS' UTC string in
--                                          SQLite; sqlite_now() below reproduces that
--                                          exact string so the application contract is
--                                          unchanged, not "modernized" to timestamptz.
--
-- Do NOT hand-edit table definitions here after this lands — add a new
-- numbered migration file instead.
-- ============================================================================

-- Reproduces SQLite's CURRENT_TIMESTAMP / datetime('now') column-default
-- string exactly ('YYYY-MM-DD HH:MM:SS', UTC, no offset, no fractional
-- seconds) so every TEXT timestamp column's on-disk format is unchanged.
CREATE OR REPLACE FUNCTION sqlite_now() RETURNS TEXT AS $$
  SELECT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS');
$$ LANGUAGE SQL STABLE;

-- Reproduces SQLite's date('now') exactly ('YYYY-MM-DD', UTC date only).
-- IMPORTANT: use this (not sqlite_now()) wherever the comparison is against
-- a date-only TEXT column (e.g. events.event_date) — comparing a date-only
-- string against a full timestamp string breaks lexicographic ">="/"<="
-- comparisons for part of the day. Caught during Phase 4 SQL porting
-- (admin.py's "upcoming events" filter) — see migration report Phase 4/G.
CREATE OR REPLACE FUNCTION sqlite_today() RETURNS TEXT AS $$
  SELECT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD');
$$ LANGUAGE SQL STABLE;


-- ── Core: parents / athletes / logins ───────────────────────────────────────

CREATE TABLE parents (
    id                        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name                 TEXT NOT NULL,
    email                     TEXT UNIQUE NOT NULL,
    consent_timestamp         TEXT NOT NULL,
    consent_confirmed         BOOLEAN DEFAULT FALSE,
    created_at                TEXT DEFAULT sqlite_now(),
    last_login_at             TEXT,
    blueprint_first_viewed_at TEXT,
    phone                     TEXT DEFAULT NULL
);

CREATE TABLE athletes (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id            INTEGER REFERENCES parents(id),
    first_name           TEXT NOT NULL,
    age                  INTEGER NOT NULL,
    date_of_birth        TEXT NULL,
    gender               TEXT NOT NULL,
    weight_lbs           DOUBLE PRECISION NOT NULL,
    height_ft            INTEGER NOT NULL,
    height_in            DOUBLE PRECISION NOT NULL,
    position             TEXT,
    competition_level    TEXT,
    sweat_profile        TEXT,
    allergies            TEXT,
    dietary_restrictions TEXT,
    supplement_use       TEXT,
    blueprint_json       TEXT,
    created_at           TEXT DEFAULT sqlite_now(),
    season_phase         TEXT DEFAULT 'in_season',
    food_preferences     TEXT DEFAULT NULL,
    lifestyle_activity   TEXT DEFAULT 'light',
    diet_pref            TEXT DEFAULT 'omnivore',
    byga_ics_url         TEXT,
    playmetrics_ics_url  TEXT,
    phone                TEXT DEFAULT NULL,
    wind_down_dismissed  INTEGER DEFAULT 0
);

CREATE TABLE athlete_logins (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      TEXT UNIQUE NOT NULL,
    athlete_id INTEGER NOT NULL UNIQUE REFERENCES athletes(id) ON DELETE CASCADE,
    created_at TEXT DEFAULT sqlite_now()
);
CREATE INDEX idx_athlete_logins_email ON athlete_logins(email);

CREATE TABLE athlete_food_prefs (
    athlete_id INTEGER NOT NULL,
    food_name  TEXT NOT NULL,
    preference TEXT NOT NULL,
    category   TEXT,
    PRIMARY KEY (athlete_id, food_name)
);

CREATE TABLE account_deletion_requests (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id     INTEGER NOT NULL REFERENCES parents(id),
    parent_name   TEXT NOT NULL,
    parent_email  TEXT NOT NULL,
    athlete_names TEXT,
    created_at    TEXT DEFAULT sqlite_now()
);

CREATE TABLE otp_codes (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id  INTEGER NOT NULL REFERENCES parents(id) ON DELETE CASCADE,
    code_hash  TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    used       INTEGER DEFAULT 0,
    created_at TEXT DEFAULT sqlite_now()
);
CREATE INDEX idx_otp_parent ON otp_codes(parent_id, used, expires_at);


-- ── Schedule / events ────────────────────────────────────────────────────────

CREATE TABLE events (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id      INTEGER REFERENCES athletes(id),
    event_name      TEXT NOT NULL,
    event_type      TEXT NOT NULL,
    event_date      TEXT NOT NULL,
    start_time      TEXT,
    duration_hours  DOUBLE PRECISION,
    city            TEXT,
    created_at      TEXT DEFAULT sqlite_now(),
    intensity       TEXT,
    venue_name      TEXT,
    address         TEXT,
    latitude        DOUBLE PRECISION,
    longitude       DOUBLE PRECISION,
    activity_type   TEXT DEFAULT NULL,
    uid             TEXT,
    source          TEXT DEFAULT 'manual',
    synced_at       TEXT
);
CREATE INDEX idx_events_athlete_source ON events(athlete_id, source);
CREATE UNIQUE INDEX idx_events_athlete_uid ON events(athlete_id, uid) WHERE uid IS NOT NULL;


-- ── Fueling: confirmations / logs / targets ─────────────────────────────────

CREATE TABLE confirmations (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id  INTEGER NOT NULL REFERENCES athletes(id),
    log_date    TEXT NOT NULL,
    window_key  TEXT NOT NULL,
    window_type TEXT NOT NULL,
    created_at  TEXT NOT NULL DEFAULT sqlite_now(),
    UNIQUE (athlete_id, window_key, log_date)
);
CREATE INDEX idx_confirmations_athlete_date ON confirmations (athlete_id, log_date);

CREATE TABLE daily_targets (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id       INTEGER REFERENCES athletes(id),
    target_date      TEXT NOT NULL,
    event_type       TEXT,
    total_calories   INTEGER,
    carbs_g_min      INTEGER,
    carbs_g_max      INTEGER,
    protein_g_min    INTEGER,
    protein_g_max    INTEGER,
    fat_g_min        INTEGER,
    fat_g_max        INTEGER,
    iron_mg          INTEGER,
    calcium_mg       INTEGER,
    hydration_oz_min INTEGER,
    hydration_oz_max INTEGER,
    lea_alert        BOOLEAN,
    targets_raw      TEXT,
    intensity        TEXT,
    UNIQUE (athlete_id, target_date)
);

CREATE TABLE fueling_window_log (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id  INTEGER NOT NULL REFERENCES athletes(id),
    date        TEXT NOT NULL,
    window_slot TEXT NOT NULL,
    applicable  INTEGER NOT NULL DEFAULT 1,
    completed   INTEGER NOT NULL DEFAULT 0,
    logged_at   TEXT DEFAULT sqlite_now(),
    UNIQUE (athlete_id, date, window_slot)
);

CREATE TABLE window_logs (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id      INTEGER NOT NULL,
    window_id       TEXT NOT NULL,
    log_date        TEXT NOT NULL,
    method          TEXT NOT NULL DEFAULT 'photo',
    text            TEXT,
    photo_url       TEXT,
    thumb_url       TEXT,
    audio_url       TEXT,
    nutrient_status TEXT NOT NULL DEFAULT 'none',
    logged_by       TEXT,
    created_at      TEXT DEFAULT sqlite_now(),
    UNIQUE(athlete_id, window_id, log_date)
);

CREATE TABLE meal_logs (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id  INTEGER REFERENCES athletes(id),
    logged_at   TEXT DEFAULT sqlite_now(),
    log_method  TEXT NOT NULL,
    description TEXT,
    calories    DOUBLE PRECISION,
    carbs_g     DOUBLE PRECISION,
    protein_g   DOUBLE PRECISION,
    fat_g       DOUBLE PRECISION,
    iron_mg     DOUBLE PRECISION,
    calcium_mg  DOUBLE PRECISION,
    water_oz    DOUBLE PRECISION,
    edamam_raw  TEXT
);

CREATE TABLE water_logs (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id INTEGER REFERENCES athletes(id),
    log_date   TEXT NOT NULL,
    cups       INTEGER NOT NULL DEFAULT 0,
    updated_at TEXT DEFAULT sqlite_now(),
    UNIQUE(athlete_id, log_date)
);


-- ── Meal planning / recipes / shopping ──────────────────────────────────────

CREATE TABLE meal_plans (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id      INTEGER NOT NULL REFERENCES athletes(id) ON DELETE CASCADE,
    plan_date       TEXT NOT NULL,
    slot_name       TEXT NOT NULL,
    recipe_id       TEXT,
    recipe_name     TEXT,
    calories        DOUBLE PRECISION,
    carbs_g         DOUBLE PRECISION,
    protein_g       DOUBLE PRECISION,
    fat_g           DOUBLE PRECISION,
    is_ai_generated INTEGER DEFAULT 0,
    logged          INTEGER DEFAULT 0,
    created_at      TEXT DEFAULT sqlite_now(),
    UNIQUE(athlete_id, plan_date, slot_name)
);
CREATE INDEX idx_meal_plans_athlete_date ON meal_plans(athlete_id, plan_date);

CREATE TABLE meal_plan_selections (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id  INTEGER NOT NULL REFERENCES athletes(id) ON DELETE CASCADE,
    plan_date   TEXT NOT NULL,
    window_key  TEXT NOT NULL,
    item_text   TEXT NOT NULL,
    recipe_json TEXT,
    added_by    TEXT NOT NULL DEFAULT 'parent',
    created_at  TEXT DEFAULT sqlite_now()
);
CREATE INDEX idx_meal_plan_selections_athlete_date ON meal_plan_selections(athlete_id, plan_date);

CREATE TABLE recipe_selections (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id         INTEGER NOT NULL REFERENCES athletes(id),
    week_start         TEXT NOT NULL,
    selection_date     TEXT NOT NULL,
    fueling_window_key TEXT NOT NULL,
    recipe_id          TEXT NOT NULL,
    servings           INTEGER NOT NULL DEFAULT 1,
    created_at         TEXT NOT NULL DEFAULT sqlite_now(),
    updated_at         TEXT NOT NULL DEFAULT sqlite_now(),
    UNIQUE (athlete_id, week_start, fueling_window_key, recipe_id)
);
CREATE INDEX idx_recipe_selections_athlete_week ON recipe_selections (athlete_id, week_start);

CREATE TABLE recipe_lists (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id INTEGER NOT NULL REFERENCES athletes(id),
    week_start TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT sqlite_now(),
    UNIQUE (athlete_id, week_start)
);

CREATE TABLE recipe_list_items (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    list_id         INTEGER NOT NULL REFERENCES recipe_lists(id),
    name            TEXT NOT NULL,
    checked         INTEGER NOT NULL DEFAULT 0,
    created_at      TEXT NOT NULL DEFAULT sqlite_now(),
    category        TEXT NOT NULL DEFAULT 'other',
    ingredient_type TEXT NOT NULL DEFAULT 'main',
    UNIQUE (list_id, name)
);
CREATE INDEX idx_recipe_list_items_list ON recipe_list_items (list_id);

CREATE TABLE recipe_list_item_sources (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    list_item_id INTEGER NOT NULL REFERENCES recipe_list_items(id) ON DELETE CASCADE,
    recipe_id    TEXT NOT NULL,
    recipe_name  TEXT NOT NULL,
    created_at   TEXT NOT NULL DEFAULT sqlite_now(),
    UNIQUE (list_item_id, recipe_id)
);
CREATE INDEX idx_recipe_list_item_sources_item ON recipe_list_item_sources (list_item_id);

CREATE TABLE pantry_list_items (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id    INTEGER NOT NULL,
    week_start    TEXT NOT NULL,
    food_id       TEXT NOT NULL,
    name          TEXT NOT NULL,
    cue_label     TEXT,
    purchase_unit TEXT,
    role          TEXT,
    meal_context  TEXT,
    must_have     INTEGER NOT NULL DEFAULT 0,
    checked       INTEGER NOT NULL DEFAULT 0,
    created_at    TEXT NOT NULL DEFAULT sqlite_now(),
    UNIQUE (athlete_id, week_start, food_id)
);
CREATE INDEX idx_pantry_athlete_week ON pantry_list_items (athlete_id, week_start);

CREATE TABLE shopping_lists (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id INTEGER NOT NULL,
    week_start TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT sqlite_now(),
    UNIQUE (athlete_id, week_start)
);

CREATE TABLE shopping_list_items (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    list_id    INTEGER NOT NULL REFERENCES shopping_lists(id),
    name       TEXT NOT NULL,
    category   TEXT NOT NULL,
    source     TEXT NOT NULL DEFAULT 'suggested',
    checked    INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT sqlite_now()
);

CREATE TABLE fueling_foods (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT NOT NULL UNIQUE,
    category      TEXT NOT NULL,
    role          TEXT,
    allergen_tags TEXT DEFAULT '',
    soft_hint     TEXT DEFAULT '',
    is_active     INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE food_submissions (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               TEXT NOT NULL,
    suggested_category TEXT,
    submitted_by       INTEGER NOT NULL,
    status             TEXT NOT NULL DEFAULT 'pending',
    created_at         TEXT NOT NULL DEFAULT sqlite_now()
);


-- ── Notifications / push ────────────────────────────────────────────────────

CREATE TABLE push_subscriptions (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id            INTEGER REFERENCES athletes(id),
    endpoint              TEXT NOT NULL,
    p256dh                TEXT NOT NULL,
    auth                  TEXT NOT NULL,
    remind_pregame_meal   INTEGER DEFAULT 1,
    remind_pregame_snack  INTEGER DEFAULT 1,
    remind_meal_log       INTEGER DEFAULT 1,
    remind_hydration      INTEGER DEFAULT 1,
    created_at            TEXT DEFAULT sqlite_now(),
    UNIQUE(athlete_id, endpoint)
);

CREATE TABLE expo_push_tokens (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id INTEGER,
    parent_id  INTEGER,
    token      TEXT NOT NULL UNIQUE,
    platform   TEXT,
    created_at TEXT NOT NULL DEFAULT sqlite_now(),
    updated_at TEXT NOT NULL DEFAULT sqlite_now(),
    timezone   TEXT
);
CREATE INDEX idx_expo_tokens_athlete ON expo_push_tokens (athlete_id);
CREATE INDEX idx_expo_tokens_parent ON expo_push_tokens (parent_id);

CREATE TABLE expo_push_log (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    success    INTEGER NOT NULL,
    detail     TEXT,
    created_at TEXT NOT NULL DEFAULT sqlite_now()
);
CREATE INDEX idx_expo_push_log_created ON expo_push_log(created_at);

CREATE TABLE notification_log (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id INTEGER NOT NULL,
    window_key TEXT NOT NULL,
    send_date  TEXT NOT NULL,
    recipient  TEXT NOT NULL DEFAULT 'athlete',
    token      TEXT NOT NULL,
    sent_at    TEXT NOT NULL DEFAULT sqlite_now(),
    UNIQUE (athlete_id, window_key, send_date, recipient)
);

CREATE TABLE notification_prefs (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_type        TEXT NOT NULL,
    profile_id          INTEGER NOT NULL,
    training_days       INTEGER NOT NULL DEFAULT 1,
    game_days           INTEGER NOT NULL DEFAULT 1,
    quiet_hours_enabled INTEGER NOT NULL DEFAULT 1,
    quiet_start         TEXT NOT NULL DEFAULT '22:00',
    quiet_end           TEXT NOT NULL DEFAULT '07:00',
    updated_at          TEXT NOT NULL DEFAULT sqlite_now(),
    UNIQUE(profile_type, profile_id)
);


-- ── Reports / config ─────────────────────────────────────────────────────────

CREATE TABLE report_config (
    key         TEXT PRIMARY KEY,
    value       DOUBLE PRECISION NOT NULL,
    description TEXT,
    updated_at  TEXT NOT NULL DEFAULT sqlite_now()
);


-- ── Content: articles / legal / knowledge ───────────────────────────────────

CREATE TABLE articles (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          TEXT NOT NULL,
    summary        TEXT NOT NULL,
    body_markdown  TEXT NOT NULL,
    category       TEXT NOT NULL,
    audience       TEXT DEFAULT 'both',
    read_time_min  INTEGER NOT NULL,
    author         TEXT DEFAULT 'Purvi Shah MS RDN',
    science_source TEXT,
    published_date TEXT NOT NULL,
    is_active      INTEGER DEFAULT 1,
    created_at     TEXT DEFAULT sqlite_now()
);

CREATE TABLE athlete_article_picks (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id   INTEGER NOT NULL REFERENCES athletes(id),
    article_id   INTEGER NOT NULL REFERENCES articles(id),
    week_start   TEXT NOT NULL,
    alex_reason  TEXT NOT NULL,
    generated_at TEXT DEFAULT sqlite_now(),
    UNIQUE(athlete_id, article_id, week_start)
);

CREATE TABLE legal_documents (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug       TEXT UNIQUE NOT NULL,
    title      TEXT NOT NULL,
    content    TEXT NOT NULL DEFAULT '',
    updated_at TEXT DEFAULT sqlite_now()
);

CREATE TABLE knowledge_items (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug                 TEXT UNIQUE NOT NULL,
    title                TEXT NOT NULL,
    category             TEXT NOT NULL,
    source               TEXT,
    source_urls          TEXT,
    last_reviewed_date   TEXT,
    organization         TEXT,
    applicable_age_range TEXT,
    tags                 TEXT,
    review_status        TEXT DEFAULT 'draft',
    version              INTEGER DEFAULT 1,
    file_path            TEXT NOT NULL,
    ingested_at          TEXT DEFAULT sqlite_now()
);
CREATE INDEX idx_knowledge_items_status ON knowledge_items(review_status);

CREATE TABLE knowledge_chunks (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id         INTEGER REFERENCES knowledge_items(id) ON DELETE CASCADE,
    chunk_index     INTEGER NOT NULL,
    heading         TEXT,
    content         TEXT NOT NULL,
    embedding       TEXT,
    embedding_model TEXT,
    created_at      TEXT DEFAULT sqlite_now()
);
CREATE INDEX idx_knowledge_chunks_item ON knowledge_chunks(item_id);


-- ── Coach / dietitian / feedback / support ──────────────────────────────────

CREATE TABLE coach_feedback (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating         TEXT NOT NULL,
    question       TEXT,
    answer_excerpt TEXT,
    window_key     TEXT,
    recipe_intent  INTEGER,
    role_hint      TEXT,
    reason         TEXT,
    created_at     TEXT DEFAULT sqlite_now()
);

CREATE TABLE dietitian_bookings (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id    INTEGER NOT NULL REFERENCES athletes(id),
    session_type  TEXT NOT NULL,
    about_athlete TEXT NOT NULL,
    reason        TEXT,
    created_at    TEXT DEFAULT sqlite_now()
);

CREATE TABLE feature_requests (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email        TEXT,
    athlete_id   INTEGER,
    suggestion   TEXT NOT NULL,
    reason       TEXT,
    submitted_at TEXT DEFAULT sqlite_now()
);

CREATE TABLE problem_reports (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description    TEXT NOT NULL,
    screenshot_url TEXT,
    app_version    TEXT,
    platform       TEXT,
    role_hint      TEXT,
    created_at     TEXT DEFAULT sqlite_now(),
    category       TEXT
);

CREATE TABLE instacart_handoff_feedback (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id      INTEGER,
    outcome         TEXT NOT NULL,
    would_use_again TEXT NOT NULL,
    comment         TEXT,
    created_at      TEXT DEFAULT sqlite_now()
);


-- ── Fuel IQ ──────────────────────────────────────────────────────────────────

CREATE TABLE fueliq_lessons (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level           INTEGER NOT NULL,
    order_in_level  INTEGER NOT NULL,
    is_myth         INTEGER NOT NULL DEFAULT 0,
    title           TEXT NOT NULL,
    hook            TEXT NOT NULL,
    fact_body       TEXT,
    visual_ref      TEXT,
    takeaway        TEXT,
    verdict         TEXT,
    science_text    TEXT,
    category        TEXT,
    source_citation TEXT NOT NULL,
    points          INTEGER NOT NULL DEFAULT 10,
    review_status   TEXT NOT NULL DEFAULT 'draft',
    reviewed_by     TEXT,
    review_date     TEXT,
    created_at      TEXT NOT NULL DEFAULT sqlite_now()
);

CREATE TABLE fueliq_questions (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id         INTEGER NOT NULL REFERENCES fueliq_lessons(id),
    question_text     TEXT NOT NULL,
    option_a          TEXT NOT NULL,
    option_b          TEXT NOT NULL,
    option_c          TEXT,
    correct_option    TEXT NOT NULL,
    explanation       TEXT NOT NULL,
    misconception_tag TEXT,
    order_in_lesson   INTEGER NOT NULL
);

CREATE TABLE fueliq_lesson_completions (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id    INTEGER NOT NULL REFERENCES athletes(id),
    lesson_id     INTEGER NOT NULL REFERENCES fueliq_lessons(id),
    perfect_quiz  INTEGER NOT NULL DEFAULT 0,
    points_earned INTEGER NOT NULL,
    completed_at  TEXT NOT NULL DEFAULT sqlite_now(),
    UNIQUE (athlete_id, lesson_id)
);

CREATE TABLE fueliq_quiz_attempts (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id        INTEGER NOT NULL REFERENCES athletes(id),
    question_id       INTEGER NOT NULL REFERENCES fueliq_questions(id),
    selected_option   TEXT NOT NULL,
    correct           INTEGER NOT NULL,
    misconception_tag TEXT,
    answered_at       TEXT NOT NULL DEFAULT sqlite_now()
);

CREATE TABLE fueliq_athlete_progress (
    athlete_id                INTEGER PRIMARY KEY REFERENCES athletes(id),
    score                     INTEGER NOT NULL DEFAULT 50,
    current_streak            INTEGER NOT NULL DEFAULT 0,
    best_streak               INTEGER NOT NULL DEFAULT 0,
    freeze_tokens             INTEGER NOT NULL DEFAULT 1,
    last_activity_date        TEXT,
    last_celebrated_milestone INTEGER NOT NULL DEFAULT 0,
    updated_at                TEXT NOT NULL DEFAULT sqlite_now()
);

CREATE TABLE fueliq_badges_earned (
    athlete_id INTEGER NOT NULL REFERENCES athletes(id),
    badge_key  TEXT NOT NULL,
    earned_at  TEXT NOT NULL DEFAULT sqlite_now(),
    UNIQUE (athlete_id, badge_key)
);

CREATE TABLE fueliq_daily_challenges (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    challenge_date  TEXT NOT NULL UNIQUE,
    title           TEXT NOT NULL,
    hook            TEXT NOT NULL,
    verdict         TEXT NOT NULL,
    science_text    TEXT NOT NULL,
    source_citation TEXT,
    points          INTEGER NOT NULL DEFAULT 10,
    created_at      TEXT NOT NULL DEFAULT sqlite_now(),
    push_sent_at    TEXT
);

CREATE TABLE fueliq_daily_challenge_answers (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id     INTEGER NOT NULL REFERENCES athletes(id),
    challenge_date TEXT NOT NULL,
    guess          TEXT NOT NULL,
    correct        INTEGER NOT NULL,
    answered_at    TEXT NOT NULL DEFAULT sqlite_now(),
    UNIQUE (athlete_id, challenge_date)
);

CREATE TABLE fueliq_daily_challenge_streak (
    athlete_id          INTEGER PRIMARY KEY REFERENCES athletes(id),
    current_streak      INTEGER NOT NULL DEFAULT 0,
    best_streak         INTEGER NOT NULL DEFAULT 0,
    last_completed_date TEXT,
    updated_at          TEXT NOT NULL DEFAULT sqlite_now()
);

CREATE TABLE fueliq_notification_prefs (
    athlete_id      INTEGER PRIMARY KEY REFERENCES athletes(id),
    morning_enabled INTEGER NOT NULL DEFAULT 1,
    pregame_enabled INTEGER NOT NULL DEFAULT 1,
    updated_at      TEXT NOT NULL DEFAULT sqlite_now()
);

CREATE TABLE fueliq_push_events (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id INTEGER NOT NULL,
    trigger    TEXT NOT NULL,
    outcome    TEXT NOT NULL,
    event_date TEXT NOT NULL,
    logged_at  TEXT NOT NULL DEFAULT sqlite_now(),
    UNIQUE (athlete_id, trigger, outcome, event_date)
);

CREATE TABLE streak_state (
    athlete_id                INTEGER PRIMARY KEY,
    freeze_tokens             INTEGER NOT NULL DEFAULT 1,
    last_celebrated_milestone INTEGER NOT NULL DEFAULT 0,
    updated_at                TEXT NOT NULL DEFAULT sqlite_now()
);


-- ── TeamCoach: coaches / teams / roster / snapshots ─────────────────────────

CREATE TABLE coaches (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             TEXT NOT NULL,
    email            TEXT UNIQUE NOT NULL,
    auth_provider_id TEXT NULL,
    password_hash    TEXT NULL,
    salt             TEXT NULL,
    created_at       TEXT DEFAULT sqlite_now()
);

CREATE TABLE teams (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT NOT NULL,
    season        TEXT NOT NULL,
    club_id       INTEGER NULL,
    threshold_pct INTEGER NOT NULL DEFAULT 80,
    created_at    TEXT DEFAULT sqlite_now()
);

CREATE TABLE coach_team_access (
    coach_id INTEGER NOT NULL REFERENCES coaches(id),
    team_id  INTEGER NOT NULL REFERENCES teams(id),
    PRIMARY KEY (coach_id, team_id)
);

CREATE TABLE roster_membership (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id          INTEGER NOT NULL REFERENCES athletes(id),
    team_id             INTEGER NOT NULL REFERENCES teams(id),
    parent_consent_flag INTEGER NOT NULL DEFAULT 0,
    joined_at           TEXT DEFAULT sqlite_now(),
    UNIQUE (athlete_id, team_id)
);

CREATE TABLE team_engagement_snapshot (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id                 INTEGER NOT NULL REFERENCES teams(id),
    week_start              TEXT NOT NULL,
    threshold_pct           INTEGER NOT NULL DEFAULT 80,
    players_above_threshold INTEGER NOT NULL DEFAULT 0,
    roster_count            INTEGER NOT NULL DEFAULT 0,
    generated_at            TEXT DEFAULT sqlite_now(),
    UNIQUE (team_id, week_start)
);


-- ── Admin / health / observability ──────────────────────────────────────────

CREATE TABLE admin_audit_log (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id     INTEGER NOT NULL,
    actor_email  TEXT NOT NULL,
    actor_role   TEXT NOT NULL,
    action       TEXT NOT NULL,
    target_type  TEXT NOT NULL,
    target_id    INTEGER NOT NULL,
    target_email TEXT,
    before_state TEXT,
    after_state  TEXT,
    request_ip   TEXT,
    user_agent   TEXT,
    created_at   TEXT NOT NULL DEFAULT sqlite_now()
);
CREATE INDEX idx_admin_audit_created ON admin_audit_log(created_at);

CREATE TABLE health_checks (
    check_name      TEXT PRIMARY KEY,
    status          TEXT NOT NULL DEFAULT 'unknown',
    detail          TEXT,
    metric_value    DOUBLE PRECISION,
    last_checked_at TEXT,
    last_green_at   TEXT,
    last_red_at     TEXT,
    last_alerted_at TEXT
);

CREATE TABLE health_incidents (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    check_name  TEXT NOT NULL,
    from_status TEXT,
    to_status   TEXT,
    detail      TEXT,
    created_at  TEXT NOT NULL DEFAULT sqlite_now()
);
CREATE INDEX idx_health_incidents_check ON health_incidents(check_name, created_at);
CREATE INDEX idx_health_incidents_created ON health_incidents(created_at);

CREATE TABLE health_scratch (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    v  TEXT
);

CREATE TABLE scheduler_heartbeats (
    job_name        TEXT PRIMARY KEY,
    last_run_at     TEXT,
    last_success_at TEXT,
    last_error      TEXT,
    meta            TEXT
);
