-- auth v2.1 Phase 5: common identity resolver foundation.
--
-- auth_identities maps a verified authentication-provider identity
-- (provider + provider_subject) to exactly one existing AthFuelPath parent
-- or athlete. provider_subject is the STABLE authoritative key; email is
-- non-authoritative metadata (for the "email" provider they happen to be
-- the same normalized string, since email itself IS the trust mechanism
-- for that provider -- see the Phase 5 plan, section B.2).
--
-- Additive only. Does not touch parents/athlete_logins. Safe to apply to
-- production before the application code that reads/writes this table
-- ships -- the table simply goes unused until then.
--
-- FAIL-CLOSED PREFLIGHT (2026-08-24 review, mandatory): a 2026-08-24
-- planning-time check found zero collisions, but production data can
-- change between planning and the moment this file actually runs. This
-- migration therefore re-checks for collisions at EXECUTION time and
-- aborts the entire file (CREATE TABLE included -- one transaction per
-- migration file, per db/postgres_migrate.py's run_migrations) rather
-- than guessing an owner or partially backfilling. If this RAISEs, the
-- migration runner rolls back and stops -- rerun only after resolving the
-- reported collision by hand.
--
-- TOCTOU CLOSE (code review, 2026-08-24): under the default READ COMMITTED
-- isolation, a concurrent write landing between the preflight SELECT and
-- the later backfill INSERT...SELECT would not be caught by the preflight,
-- and ON CONFLICT DO NOTHING would silently drop the colliding row --
-- permanently, since schema_migrations marks this file applied afterward.
-- REPEATABLE READ makes the preflight and both backfill inserts see one
-- consistent snapshot: any such race is either caught by the preflight's
-- RAISE EXCEPTION, or aborts the whole transaction with a Postgres
-- serialization failure (also rolled back by the migration runner) --
-- never a silent partial write.

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;

DO $$
DECLARE
    dup_parent_count INTEGER;
    dup_athlete_login_count INTEGER;
    overlap_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO dup_parent_count FROM (
        SELECT lower(trim(email)) FROM parents GROUP BY 1 HAVING COUNT(*) > 1
    ) t;
    SELECT COUNT(*) INTO dup_athlete_login_count FROM (
        SELECT lower(trim(email)) FROM athlete_logins GROUP BY 1 HAVING COUNT(*) > 1
    ) t;
    SELECT COUNT(*) INTO overlap_count FROM parents p
        JOIN athlete_logins a ON lower(trim(p.email)) = lower(trim(a.email));

    IF dup_parent_count > 0 OR dup_athlete_login_count > 0 OR overlap_count > 0 THEN
        RAISE EXCEPTION
            'auth_identities backfill aborted: % duplicate parent email group(s), % duplicate athlete_login email group(s), % parent/athlete email overlap(s) found at migration time. Resolve manually before rerunning -- do not guess an owner.',
            dup_parent_count, dup_athlete_login_count, overlap_count;
    END IF;
END $$;

CREATE TABLE auth_identities (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider         TEXT NOT NULL CHECK (provider IN ('email', 'google', 'apple')),
    provider_subject TEXT NOT NULL,
    parent_id        INTEGER REFERENCES parents(id) ON DELETE CASCADE,
    athlete_id       INTEGER REFERENCES athletes(id) ON DELETE CASCADE,
    email            TEXT,
    email_verified   BOOLEAN NOT NULL DEFAULT FALSE,
    created_at       TEXT NOT NULL DEFAULT sqlite_now(),
    updated_at       TEXT NOT NULL DEFAULT sqlite_now(),

    CONSTRAINT auth_identities_provider_subject_uniq UNIQUE (provider, provider_subject),
    CONSTRAINT auth_identities_exactly_one_owner CHECK (
        (parent_id IS NOT NULL AND athlete_id IS NULL) OR
        (parent_id IS NULL AND athlete_id IS NOT NULL)
    )
);

CREATE INDEX idx_auth_identities_parent_id ON auth_identities(parent_id);
CREATE INDEX idx_auth_identities_athlete_id ON auth_identities(athlete_id);

-- Backfill: one 'email'-provider identity row per existing parent and per
-- existing athlete login, normalized at write time (existing parents.email/
-- athlete_logins.email are NOT reliably pre-normalized in storage -- see
-- Phase 5 plan section A.5). A 2026-08-24 production preflight confirmed
-- zero normalized-email collisions across parents, across athlete_logins,
-- and between the two -- this backfill is fully deterministic, no owner
-- was guessed, and it never deletes/merges/rewrites an existing account row.

INSERT INTO auth_identities (provider, provider_subject, parent_id, email, email_verified)
SELECT 'email', lower(trim(email)), id, lower(trim(email)), TRUE
FROM parents
ON CONFLICT (provider, provider_subject) DO NOTHING;

INSERT INTO auth_identities (provider, provider_subject, athlete_id, email, email_verified)
SELECT 'email', lower(trim(email)), athlete_id, lower(trim(email)), TRUE
FROM athlete_logins
ON CONFLICT (provider, provider_subject) DO NOTHING;
