-- auth v2.1 Phase 6: (1) close the "multiple identities per owner per
-- provider" gap -- UNIQUE(provider, provider_subject) alone never
-- prevented two different Google/Apple subjects both linking to the same
-- parent or athlete. (2) add provider_auth_challenges, the server-issued
-- single-use nonce ledger backing POST /api/auth/provider/challenge --
-- replay protection for Google/Apple sign-in must not rely solely on a
-- mobile-generated nonce. Stores the RAW issued nonce (not a pre-committed
-- hash under an assumed transform) -- each provider's actual nonce-claim
-- comparison transform is empirically confirmed per-provider at Task 1
-- (see the Phase 6 plan, section A.6) and is not assumed identical
-- between Google and Apple. (3) add apple_provider_credentials, storing
-- APPLICATION-LAYER-ENCRYPTED Apple refresh tokens (AES-256-GCM, key in
-- Secret Manager, separate from APP_SESSION_SECRET) so a Phase 10 Apple
-- authorization revoke call is possible later -- never stored in
-- plaintext, never on auth_identities itself. (4) add apple_pending_links,
-- the short-lived server-side record binding an already-verified Apple
-- identity to the Hide-My-Email secondary-OTP linking flow.
-- Additive only. Does not touch 003_auth_identities.sql -- schema version
-- 3 is production history. Preflight: as of this migration's authoring,
-- all 71 existing auth_identities rows are provider='email', one per
-- parent/athlete by the Phase 5 backfill's own uniqueness guarantee --
-- zero possible violations of the new partial-unique indexes exist today;
-- re-confirm this at actual migration-execution time, not just here.

CREATE UNIQUE INDEX auth_identities_one_per_provider_per_parent
    ON auth_identities (provider, parent_id) WHERE parent_id IS NOT NULL;

CREATE UNIQUE INDEX auth_identities_one_per_provider_per_athlete
    ON auth_identities (provider, athlete_id) WHERE athlete_id IS NOT NULL;

CREATE TABLE provider_auth_challenges (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    challenge_id  TEXT NOT NULL UNIQUE,
    provider      TEXT NOT NULL CHECK (provider IN ('google', 'apple')),
    raw_nonce     TEXT NOT NULL,
    expires_at    TIMESTAMPTZ NOT NULL,
    consumed_at   TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_provider_auth_challenges_lookup
    ON provider_auth_challenges (challenge_id, provider) WHERE consumed_at IS NULL;
CREATE INDEX idx_provider_auth_challenges_expiry
    ON provider_auth_challenges (expires_at);  -- keeps A.11's opportunistic cleanup cheap

CREATE TABLE apple_provider_credentials (
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_identity_id       INTEGER NOT NULL UNIQUE REFERENCES auth_identities(id) ON DELETE CASCADE,
    encrypted_refresh_token BYTEA NOT NULL,
    encryption_nonce       BYTEA NOT NULL,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE apple_pending_links (
    id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pending_link_id          TEXT NOT NULL UNIQUE,
    provider_subject         TEXT NOT NULL,
    email_from_token         TEXT,
    email_verified_from_token BOOLEAN NOT NULL DEFAULT FALSE,
    encrypted_refresh_token  BYTEA NOT NULL,  -- NOT NULL: a pending link is only ever
    encryption_nonce         BYTEA NOT NULL,  -- created AFTER a successful exchange (A.8,
                                               -- corrected round 4) -- no credential-less
                                               -- pending link can exist in this schema
    expires_at               TIMESTAMPTZ NOT NULL,
    consumed_at              TIMESTAMPTZ,
    created_at                TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_apple_pending_links_lookup
    ON apple_pending_links (pending_link_id) WHERE consumed_at IS NULL;
CREATE INDEX idx_apple_pending_links_expiry
    ON apple_pending_links (expires_at) WHERE consumed_at IS NULL;  -- A.11's opportunistic cleanup
