-- auth v2.1: parent-initiated athlete unlink (docs/planning/
-- parent-initiated-athlete-unlink.md). Recovery path for an athlete whose
-- provider identity becomes unusable, replacing the removed
-- athlete-claim.tsx flow. Adds only an audit-log table -- the unlink
-- itself hard-deletes rows in auth_identities/athlete_logins (existing
-- tables, no schema change needed there; apple_provider_credentials
-- cascades via its existing FK). No soft-delete/tombstone anywhere --
-- the audit trail lives here, never as a retained auth_identities row.

CREATE TABLE athlete_unlink_log (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id      INTEGER NOT NULL REFERENCES athletes(id) ON DELETE CASCADE,
    actor_parent_id INTEGER NOT NULL REFERENCES parents(id),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_athlete_unlink_log_athlete_id ON athlete_unlink_log(athlete_id);
